### PR TITLE
Add launch debug command

### PR DESCRIPTION
**Pull request by A2va**
I noticed sometimes with codelldb and `stopAtEntry` set to true, there is an exception at the start. Nothing that stop the debugger to continue but it's weird because sometimes it happens sometimes not.
Should I disable `stopAtEntry` for codelldb?

### CODE REVIEW

**Comment by waruqi** [comment]
I tried this patch and select xmake to launch debugger, but it does not work.

image


image

**Comment by A2va** [comment]
I think I know, why, when a launch.json is not found and the Run and Debug button is pressed, vscode tried to call `provideDebugConfigurations` to solve it dynamically but I didn't implement it because I wanted to do it later.
What you need to do in this case is to press `create a launch.json file` and then select `xmake`.

Do I have to implement it in this PR?

**Comment by waruqi** [comment]
> I think I know, why, when a launch.json is not found and the Run and Debug button is pressed, vscode tried to call `provideDebugConfigurations` to solve it dynamically but I didn't implement it because I wanted to do it later. What you need to do in this case is to press `create a launch.json file` and then select `xmake`.
> 

I created it, it works now.

> Do I have to implement it in this PR?

You can implement it later in new pr, or you can provide a user prompt to guide the user to create it manually.

**Comment by waruqi** [comment]
Thanks!

**Comment by waruqi** [comment]
btw, please push pr to dev branch next.

**Comment by A2va** [comment]
> btw, please push pr to dev branch next.

Sorry, I should have known better

**Pull request merged**
